/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cargo.managment.system;

import Comman.OpenPdf;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dao.ShiftCargodao;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import model.ShiftCargoModel;

/**
 *
 * @author Admin
 */
public class GatePass extends javax.swing.JFrame {

    /**
     * Creates new form GatePass
     */
    public GatePass() {
        initComponents();
        btnGenerategetpass.setEnabled(false);
    }
     String wightpattern="-?\\d+(\\.\\d+)?";

    public void vaidateField() {
        String weight=txtWaight.getText();
        String orderid = (String) txtOrderId.getSelectedItem();
        String shiftedto = (String) txtshiftedwarehous.getSelectedItem();
        if (!orderid.equals("--select--") && !shiftedto.equals("--select--") && weight.matches(wightpattern)&& !weight.equals("")) {
            btnGenerategetpass.setEnabled(true);
        } else {
            btnGenerategetpass.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtOrderId = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtshiftedwarehous = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtWaight = new javax.swing.JTextField();
        btnGenerategetpass = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 250));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gate Pass");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Order Id:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 97, -1, -1));

        txtOrderId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtOrderId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--" }));
        txtOrderId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderIdActionPerformed(evt);
            }
        });
        txtOrderId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOrderIdKeyReleased(evt);
            }
        });
        getContentPane().add(txtOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 94, 175, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Shifted Warehous:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 147, -1, -1));

        txtshiftedwarehous.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtshiftedwarehous.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--" }));
        txtshiftedwarehous.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtshiftedwarehousKeyReleased(evt);
            }
        });
        getContentPane().add(txtshiftedwarehous, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 144, 175, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Weight:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 197, -1, -1));

        txtWaight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtWaight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWaightKeyReleased(evt);
            }
        });
        getContentPane().add(txtWaight, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 194, 176, -1));

        btnGenerategetpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGenerategetpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/save.png"))); // NOI18N
        btnGenerategetpass.setText("Generate Get Pass");
        btnGenerategetpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerategetpassActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerategetpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 261, -1, -1));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/close.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 11, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/700x400-dark-imperial-blue-soli.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ArrayList<ShiftCargoModel> lst = ShiftCargodao.getRecord();
        Iterator<ShiftCargoModel> itr = lst.iterator();
        while (itr.hasNext()) {
            ShiftCargoModel md = itr.next();
            txtOrderId.addItem(md.getOrderId());

        }
    }//GEN-LAST:event_formComponentShown

    private void txtOrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderIdActionPerformed
        // TODO add your handling code here:
        String orderid = (String) txtOrderId.getSelectedItem();
        ArrayList<ShiftCargoModel> lst = ShiftCargodao.getRecordByOrderid(orderid);
        Iterator<ShiftCargoModel> itr = lst.iterator();
        while (itr.hasNext()) {
            ShiftCargoModel md = itr.next();
            txtshiftedwarehous.addItem(md.getShiftedto());
        }
    }//GEN-LAST:event_txtOrderIdActionPerformed

    private void txtOrderIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOrderIdKeyReleased
        // TODO add your handling code here:
        vaidateField();
    }//GEN-LAST:event_txtOrderIdKeyReleased

    private void txtshiftedwarehousKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtshiftedwarehousKeyReleased
        // TODO add your handling code here:
        vaidateField();
    }//GEN-LAST:event_txtshiftedwarehousKeyReleased

    private void txtWaightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWaightKeyReleased
        // TODO add your handling code here:
        vaidateField();
    }//GEN-LAST:event_txtWaightKeyReleased

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnGenerategetpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerategetpassActionPerformed
        // TODO add your handling code here:
        String orderid = (String) txtOrderId.getSelectedItem();
        String shiftedto = (String) txtshiftedwarehous.getSelectedItem();
        String wight = txtWaight.getText();
        ArrayList<ShiftCargoModel> lst = ShiftCargodao.getGetPassData(orderid, shiftedto);
        Iterator<ShiftCargoModel> itr = lst.iterator();
        ShiftCargoModel md = itr.next();

        String path = "D:\\";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + "" + orderid + ".pdf"));
            doc.open();
            Paragraph cargoname = new Paragraph("                                                           Cargo Management System" + "                                   \n\n\n");
            cargoname.getFont().setStyle("bold");
            Paragraph gatepass = new Paragraph("                                                           Get Pass" + "                                   \n\n");
            cargoname.getFont().setColor(BaseColor.RED);
            cargoname.getFont().setStyle("italic");
            doc.add(cargoname);
            doc.add(gatepass);
            PdfPTable tb1 = new PdfPTable(8);
            tb1.addCell("Order Id");
            tb1.addCell("Quantity");
            tb1.addCell("Shifted Date");
            tb1.addCell("Shifted from");
            tb1.addCell("Shifted To");
            tb1.addCell("wight");
            tb1.addCell("Signatur");
            tb1.addCell("stamp");
            tb1.addCell(md.getOrderId());
            tb1.addCell(md.getQanity());
            tb1.addCell(md.getDate());
            tb1.addCell(md.getPlace());
            tb1.addCell(md.getShiftedto());
            tb1.addCell(wight);
            tb1.addCell("");
            tb1.addCell("");
            doc.add(tb1);
            OpenPdf.openByOrderId(orderid);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();

        JOptionPane.showMessageDialog(null, "Get Pass Created Successfully");
        setVisible(false);
        new GatePass().setVisible(true);

    }//GEN-LAST:event_btnGenerategetpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GatePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GatePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GatePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GatePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GatePass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGenerategetpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> txtOrderId;
    private javax.swing.JTextField txtWaight;
    private javax.swing.JComboBox<String> txtshiftedwarehous;
    // End of variables declaration//GEN-END:variables
}
