/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cargo.managment.system;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {

    String email;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    public Home(String useremail) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddWareHouse = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnOrderCargo = new javax.swing.JButton();
        btnShiftOrder = new javax.swing.JButton();
        btnViewOrder = new javax.swing.JButton();
        btnTrackCargo = new javax.swing.JButton();
        btnReorder = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnVerifyUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddWareHouse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddWareHouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/warehouse.png"))); // NOI18N
        btnAddWareHouse.setText("Add WareHouse");
        btnAddWareHouse.setMaximumSize(new java.awt.Dimension(145, 39));
        btnAddWareHouse.setMinimumSize(new java.awt.Dimension(145, 39));
        btnAddWareHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWareHouseActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddWareHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, 40));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/logout.png"))); // NOI18N
        btnLogout.setText("LogOut");
        btnLogout.setMaximumSize(new java.awt.Dimension(145, 39));
        btnLogout.setMinimumSize(new java.awt.Dimension(145, 39));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 40));

        btnOrderCargo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOrderCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/Order cargo.png"))); // NOI18N
        btnOrderCargo.setText("Order cargo");
        btnOrderCargo.setMaximumSize(new java.awt.Dimension(145, 39));
        btnOrderCargo.setMinimumSize(new java.awt.Dimension(145, 39));
        btnOrderCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderCargoActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrderCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, 40));

        btnShiftOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnShiftOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/shift oder.png"))); // NOI18N
        btnShiftOrder.setText("Shift Ordrer");
        btnShiftOrder.setMaximumSize(new java.awt.Dimension(145, 39));
        btnShiftOrder.setMinimumSize(new java.awt.Dimension(145, 39));
        btnShiftOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShiftOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnShiftOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, 40));

        btnViewOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/View Order.png"))); // NOI18N
        btnViewOrder.setText("View Order");
        btnViewOrder.setMaximumSize(new java.awt.Dimension(145, 39));
        btnViewOrder.setMinimumSize(new java.awt.Dimension(145, 39));
        btnViewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, -1, 40));

        btnTrackCargo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTrackCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/track cargo.png"))); // NOI18N
        btnTrackCargo.setText("Track cargo");
        btnTrackCargo.setMaximumSize(new java.awt.Dimension(145, 39));
        btnTrackCargo.setMinimumSize(new java.awt.Dimension(145, 39));
        btnTrackCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrackCargoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrackCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 140, -1, 40));

        btnReorder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/reorder.png"))); // NOI18N
        btnReorder.setText("Reorder");
        btnReorder.setMaximumSize(new java.awt.Dimension(145, 39));
        btnReorder.setMinimumSize(new java.awt.Dimension(145, 39));
        btnReorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReorderActionPerformed(evt);
            }
        });
        getContentPane().add(btnReorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 140, -1, 40));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/exit small.png"))); // NOI18N
        jButton8.setText("Exit");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(3056, 1117, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Admin Page");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 1230, -1));

        btnVerifyUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVerifyUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/verify users.png"))); // NOI18N
        btnVerifyUser.setText("Verfy Users");
        btnVerifyUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerifyUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 140, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/cargo_home.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddWareHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWareHouseActionPerformed
        // TODO add your handling code here:
        new AddWarehouse().setVisible(true);
    }//GEN-LAST:event_btnAddWareHouseActionPerformed

    private void btnOrderCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderCargoActionPerformed
        // TODO add your handling code here:
        new OredrCargoFrame().setVisible(true);
        
    }//GEN-LAST:event_btnOrderCargoActionPerformed

    private void btnShiftOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShiftOrderActionPerformed
        // TODO add your handling code here:
        new ShiftCargo().setVisible(true);
    }//GEN-LAST:event_btnShiftOrderActionPerformed

    private void btnViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderActionPerformed
        // TODO add your handling code here:
        new ViewOrder().setVisible(true);
    }//GEN-LAST:event_btnViewOrderActionPerformed

    private void btnTrackCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrackCargoActionPerformed
        // TODO add your handling code here:
        new TrackCargo().setVisible(true);
    }//GEN-LAST:event_btnTrackCargoActionPerformed

    private void btnVerifyUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyUserActionPerformed
        // TODO add your handling code here:
        new VerifyUser().setVisible(true);
    }//GEN-LAST:event_btnVerifyUserActionPerformed

    private void btnReorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReorderActionPerformed
        // TODO add your handling code here:
        new Reorder().setVisible(true);
    }//GEN-LAST:event_btnReorderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddWareHouse;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOrderCargo;
    private javax.swing.JButton btnReorder;
    private javax.swing.JButton btnShiftOrder;
    private javax.swing.JButton btnTrackCargo;
    private javax.swing.JButton btnVerifyUser;
    private javax.swing.JButton btnViewOrder;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    // End of variables declaration//GEN-END:variables
}
