/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cargo.managment.system;

import model.OrderCargo;
import dao.ShiftCargodao;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import model.Warehouse;
import model.ShiftCargoModel;

/**
 *
 * @author Admin
 */
public class ShiftCargo extends javax.swing.JFrame {

    /**
     * Creates new form ShiftOrder
     */
    public ShiftCargo() {
        initComponents();
        btnShift.setEnabled(false);
        txtPlace.setEditable(false);
        txtQuantity.setEditable(false);
        txtQuantityInwarehous.setEditable(false);
        txtCapacity.setEditable(false);

    }

    public void validateField() {
        String orderId = (String) txtOrderId.getSelectedItem();
        String shiftedto = (String) txtShiftedTo.getSelectedItem();
        if (!orderId.equalsIgnoreCase("select") && !orderId.equals("") && !shiftedto.equalsIgnoreCase("select") && !shiftedto.equals("")) {
            btnShift.setEnabled(true);
        } else {
            btnShift.setEnabled(false);
        }
    }

    int capacity = 0;
    int quantity = 0;
    int result = 0;

    public void Result() {
        String id = (String) txtOrderId.getSelectedItem();
        String warehous = (String) txtShiftedTo.getSelectedItem();
        capacity = Integer.parseInt(txtCapacity.getText());
        quantity = Integer.parseInt(txtQuantity.getText());
        result = capacity - quantity;
        if (quantity > capacity) {
            JOptionPane.showMessageDialog(null, "Your cargo id '" + id + "' is overloaded for '" + warehous + "' ware house \n plz try another warehouse");

        } else {
            txtQuantityInwarehous.setText(String.valueOf(result));

        }
    }

    public void clear() {
        setVisible(false);
        new ShiftCargo().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtOrderId = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtPlace = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtShiftedTo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtCapacity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtQuantityInwarehous = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnShift = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 250));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Shift Cargo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Order Id:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 138, -1, -1));

        txtOrderId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtOrderId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        txtOrderId.setToolTipText("");
        txtOrderId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 135, 197, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("place:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 188, -1, -1));

        txtPlace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 185, 197, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 238, -1, -1));

        txtQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 235, 197, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("--Shifted From--");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 99, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Shifted To:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        txtShiftedTo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtShiftedTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        txtShiftedTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShiftedToActionPerformed(evt);
            }
        });
        getContentPane().add(txtShiftedTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 197, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Capacity:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        txtCapacity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 197, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quantiy in warehous:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        txtQuantityInwarehous.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtQuantityInwarehous, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 197, -1));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/close.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        btnShift.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnShift.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/save.png"))); // NOI18N
        btnShift.setText("Shift");
        btnShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShiftActionPerformed(evt);
            }
        });
        getContentPane().add(btnShift, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 324, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("--Shifted To--");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/700x400-dark-imperial-blue-soli.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ArrayList<OrderCargo> lst = ShiftCargodao.getAllRecordsOrderCargo();
        Iterator<OrderCargo> itr = lst.iterator();
        while (itr.hasNext()) {
            OrderCargo ordercargo = itr.next();
            txtOrderId.addItem(ordercargo.getOrderid());

        }

        ArrayList<Warehouse> wareidlst = ShiftCargodao.getAllRecordsWarehous();
        Iterator<Warehouse> wareitr = wareidlst.iterator();
        while (wareitr.hasNext()) {
            Warehouse wr = wareitr.next();
            txtShiftedTo.addItem(wr.getPlace());
        }


    }//GEN-LAST:event_formComponentShown

    private void txtOrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderIdActionPerformed
        // TODO add your handling code here:
        String orderid = (String) txtOrderId.getSelectedItem();
        OrderCargo ord = ShiftCargodao.getOrderCargoField(orderid);
        txtPlace.setText(ord.getWarehouseplace());
        txtQuantity.setText(ord.getQuantity());
        validateField();
        if(!txtCapacity.getText().equals(""))
        {
            Result();
        }

    }//GEN-LAST:event_txtOrderIdActionPerformed

    private void txtShiftedToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShiftedToActionPerformed
        // TODO add your handling code here:
        String place = (String) txtShiftedTo.getSelectedItem();
        Warehouse wr = ShiftCargodao.getWarehousField(place);
        txtCapacity.setText(wr.getCapacity());
        Result();
        validateField();

    }//GEN-LAST:event_txtShiftedToActionPerformed

    private void btnShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShiftActionPerformed
        // TODO add your handling code here:
        ShiftCargoModel model = new ShiftCargoModel();
        model.setOrderId((String) txtOrderId.getSelectedItem());
        model.setPlace(txtPlace.getText());
        model.setQanity(txtQuantity.getText());
        model.setShiftedto((String) txtShiftedTo.getSelectedItem());
        model.setCapacity(txtCapacity.getText());
        model.setQuantityinwarehouse(txtQuantityInwarehous.getText());

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        String date = dtf.format(now);
        DateTimeFormatter dtf1 = DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now1 = LocalDateTime.now();
        String time = dtf1.format(now1);
        ShiftCargodao.saveData(model, date, time);
        clear();


    }//GEN-LAST:event_btnShiftActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShiftCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShiftCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShiftCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShiftCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShiftCargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnShift;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCapacity;
    private javax.swing.JComboBox<String> txtOrderId;
    private javax.swing.JTextField txtPlace;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtQuantityInwarehous;
    private javax.swing.JComboBox<String> txtShiftedTo;
    // End of variables declaration//GEN-END:variables
}
