/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cargo.managment.system;

/**
 *
 * @author Admin
 */
public class userHome extends javax.swing.JFrame {

    /**
     * Creates new form userHome
     */
    public userHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        btnDispatch = new javax.swing.JButton();
        btnDamageGoods = new javax.swing.JButton();
        btnGatepass = new javax.swing.JButton();
        btnContactus = new javax.swing.JButton();
        btnAboutus = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1600, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("User Page");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 1230, -1));

        btnAccept.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/verify users.png"))); // NOI18N
        btnAccept.setText("Acceptance");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        getContentPane().add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 131, -1, -1));

        btnDispatch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDispatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/delivery-truck.png"))); // NOI18N
        btnDispatch.setText("Dispatch");
        btnDispatch.setMaximumSize(new java.awt.Dimension(145, 39));
        btnDispatch.setMinimumSize(new java.awt.Dimension(145, 39));
        btnDispatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDispatchActionPerformed(evt);
            }
        });
        getContentPane().add(btnDispatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 131, 140, 40));

        btnDamageGoods.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDamageGoods.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/change Security Question.png"))); // NOI18N
        btnDamageGoods.setText("Damage Goods");
        btnDamageGoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDamageGoodsActionPerformed(evt);
            }
        });
        getContentPane().add(btnDamageGoods, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 131, -1, -1));

        btnGatepass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGatepass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/gate.png"))); // NOI18N
        btnGatepass.setText("Gate Pass");
        btnGatepass.setMaximumSize(new java.awt.Dimension(145, 39));
        btnGatepass.setMinimumSize(new java.awt.Dimension(145, 39));
        btnGatepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGatepassActionPerformed(evt);
            }
        });
        getContentPane().add(btnGatepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 134, 140, 40));

        btnContactus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnContactus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/phone.png"))); // NOI18N
        btnContactus.setText("Contact Us");
        btnContactus.setMaximumSize(new java.awt.Dimension(145, 39));
        btnContactus.setMinimumSize(new java.awt.Dimension(145, 39));
        btnContactus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactusActionPerformed(evt);
            }
        });
        getContentPane().add(btnContactus, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 134, 140, -1));

        btnAboutus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAboutus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/about us.png"))); // NOI18N
        btnAboutus.setText("About Us");
        btnAboutus.setMaximumSize(new java.awt.Dimension(145, 39));
        btnAboutus.setMinimumSize(new java.awt.Dimension(145, 39));
        btnAboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutusActionPerformed(evt);
            }
        });
        getContentPane().add(btnAboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 134, -1, -1));

        btnLogOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/logout.png"))); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.setMaximumSize(new java.awt.Dimension(145, 39));
        btnLogOut.setMinimumSize(new java.awt.Dimension(145, 39));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1439, 131, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cargoImages/cargo_home.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        new AcceptCargo().setVisible(true);
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnDispatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDispatchActionPerformed
        // TODO add your handling code here:
        new DispatchCargo().setVisible(true);
    }//GEN-LAST:event_btnDispatchActionPerformed

    private void btnDamageGoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDamageGoodsActionPerformed
        // TODO add your handling code here:
        new DamageGoods().setVisible(true);
    }//GEN-LAST:event_btnDamageGoodsActionPerformed

    private void btnGatepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGatepassActionPerformed
        // TODO add your handling code here:
        new GatePass().setVisible(true);
    }//GEN-LAST:event_btnGatepassActionPerformed

    private void btnContactusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactusActionPerformed
        // TODO add your handling code here:
        new ContactUs().setVisible(true);
    }//GEN-LAST:event_btnContactusActionPerformed

    private void btnAboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutusActionPerformed
        // TODO add your handling code here:
        new AboutUs().setVisible(true);
    }//GEN-LAST:event_btnAboutusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutus;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnContactus;
    private javax.swing.JButton btnDamageGoods;
    private javax.swing.JButton btnDispatch;
    private javax.swing.JButton btnGatepass;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    // End of variables declaration//GEN-END:variables
}
